### ISSUE TITLE
Attempting to add to debug-notes does nothing

### ISSUE THREAD

**Issue by domportera** [yannicklerestif/debug-notes#1]
This plugin looks absolutely amazing, so thank you for making it! Major kudos. I am very eager to use it, however I haven't been able to get anything to enter the debug-notes plugin through the context menu. What could I be missing here? I'm on the latest version pushed to the jetbrains marketplace

**Comment by yannicklerestif** [comment]
Hello, and thank you for your interest!
Both "Add Method" and "Add Call"?
Could you please send a gif reproducing the bug? E.g. ShareX and ScreenToGif
That would answer most of my questions :)
Thanks in advance!

**Comment by domportera** [comment]
Hey! It's currently working for me in a pretty barebones .Net Core 7 project, I will check it out on a Big Project soon.

When I posted this, I was having trouble getting it to work with a unity project

**Comment by yannicklerestif** [comment]
Cool you got it working!
If you can reproduce the issue on your unity project, can you please post a gif showing the issue?
If not no worries I'll close this issue and you can always create another one if the issue happens again 🙂

**Comment by domportera** [comment]
I got it working with unity, I'm not sure what I was doing wrong before. it's possible I caused some silent errors before I opened the debug panel. I think it's safe to close this  until I can reproduce my issue, it's possible the issue would be a feature request or a bug idk 🤷‍♂️
